/**:
    ros__parameters:
      video_device: "/dev/video1"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "usb_cam"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      av_device_format: "YUV422P"
      image_width: 1920
      image_height: 1080
      camera_name: "usb_cam"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1