# linear and angular speed limits for the robot
max_v: 0.3 #0.4 # m/s
max_w: 0.3 #0.8 # rad/s
# observation rate fo the robot
frame_rate: 10 # Hz
graph_rate: 0.3333 # Hz  

# topic names (modify for different robots/nodes)
vel_teleop_topic: /ad_r1m_13/cmd_vel #/cmd_vel_mux/input/teleop #RosAria, #panther
vel_navi_topic: /ad_r1m_13/cmd_vel #/cmd_vel_mux/input/navi #RosAria, #panther
vel_recovery_topic: /cmd_vel_mux/input/recovery


